brew 'asdf'
brew 'docker-compose'
brew 'ffmpeg'
brew 'git'
brew 'gpg'
brew 'graphviz'
brew 'hub'
brew 'httpie'
brew 'imagemagick'
brew 'wget'

tap 'eddieantonio/eddieantonio'
brew 'imgcat'

cask_args appdir: "/Applications"

cask 'ccleaner'
cask 'dropbox'
cask 'docker'
cask 'iterm2'
cask 'spotify'
cask 'caffeine'
cask 'slack'
cask 'sourcetree'
# cask 'firefox'
cask 'visual-studio-code'
